sudo: false
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - pandoc
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-19mode
  - jruby-9.1.5.0
env:
  - BUNDLE_WITHOUT=secondary:development
  - BUNDLE_WITHOUT=primary:development
install:
  - curl -L https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_0.4.0_Linux_x86_64.tgz | tar -zxC $TRAVIS_BUILD_DIR/bin/
script:
  - bundle install
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH; bundle exec rake
matrix:
  allow_failures:
    - env: BUNDLE_WITHOUT=primary:development
    - rvm: ruby-head
  fast_finish: true
